### ISSUE TITLE
How to make KITTI_VEL_SCAN.mat

### ISSUE THREAD

**Issue by quanfanquanfan** [cdebeunne/edge-plan-odometry#1]
Hi, thanks for your great work.
I noticed that the input is 'KITTI_VEL_SCAN.mat', would you please show me how to construct the "KITTI_VEL_SCAN.mat" as the rosbag  
 from the Kitti dataset is not in the form of '.mat'.
thank you.

**Comment by cdebeunne** [comment]
I have just made a push with a .m file that generates the .mat file you need to run the odometry at @https://github.com/cdebeunne/edge-plan-odometry/tree/master/data

You just need to download one trajectory from the kitti website and specify the path of the velodyne scans
